workflows:
  dexscreener_safari_ios:
    name: Dexscreener Safari iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_NAME: "DexscreenerTrader"
        BUNDLE_ID: "com.millitradez.dexscreenertrader"
        CM_API_TOKEN: Encrypted(CM_API_TOKEN)
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: 🔧 Prepare Safari Extension project
        script: |
          echo "Preparing Dexscreener Safari extension for unsigned export..."
          if [ ! -d "DexscreenerTraderExtension" ]; then
            echo "❌ DexscreenerTraderExtension folder not found. Please ensure project is in repo root."
            exit 66
          fi
          echo "✅ Extension folder found."
      - name: 🧹 Build Xcode project (clean)
        script: |
          xcodebuild clean -project Dexscreener.xcodeproj -scheme "$APP_NAME"
      - name: 📦 Archive Xcode build
        script: |
          xcodebuild archive -project Dexscreener.xcodeproj \
          -scheme "$APP_NAME" \
          -archivePath "$PWD/build/$APP_NAME.xcarchive" \
          -destination "generic/platform=iOS"
      - name: 🔑 Create unsigned IPA for AltStore
        script: |
          xcodebuild -exportArchive \
          -archivePath "$PWD/build/$APP_NAME.xcarchive" \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath "$PWD/build"
      - name: 🗜️ Compress and rename IPA
        script: |
          cd build
          zip -r "${APP_NAME}_unsigned.ipa.zip" "${APP_NAME}.ipa"
    artifacts:
      - build/${APP_NAME}_unsigned.ipa.zip
    publishing:
      scripts:
        - name: 🌐 Generate shareable artifact link
          script: |
            echo "Artifact ready for manual upload or AltStore sideload."
