workflows:
  safari_extension_convert:
    name: Safari Extension Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      vars:
        EXTENSION_NAME: "Dexscreener Trader Extension"
    scripts:
      - name: 🧹 Clean workspace
        script: |
          rm -rf safari_project
          mkdir safari_project

      - name: 🧩 Convert Chrome extension to Safari
        script: |
          echo "Converting Chrome extension to Safari..."
          xcrun safari-web-extension-converter ./ \
            --project-location safari_project \
            --app-name "${EXTENSION_NAME}" \
            --no-prompt \
            --force

      - name: 🔍 Detect available schemes
        script: |
          echo "Detecting schemes..."
          cd safari_project
          xcodebuild -list

      - name: 🚀 Build Safari extension app
        script: |
          cd safari_project
          SCHEME=$(xcodebuild -list | grep -A1 "Schemes:" | tail -n1 | xargs)
          echo "Detected scheme: $SCHEME"
          xcodebuild -scheme "$SCHEME" -configuration Release CODE_SIGNING_ALLOWED=NO

    artifacts:
      - safari_project/build/Release/
    publishing:
      email:
        recipients:
          - your@email.com
