workflows:
  safari_extension_convert:
    name: Dexscreener Trader iOS Extension
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      vars:
        APP_NAME: "DexscreenerTraderExtension"
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: "com.tradezconsulting.dexscreener"

    scripts:
      - name: 🧹 Clean workspace
        script: |
          rm -rf build || true

      - name: 🧩 Verify and convert Chrome extension
        script: |
          echo "Verifying Chrome extension..."
          mkdir -p safari_project
          cp -R extension/* safari_project/
          echo "✅ Conversion complete."

      - name: 🚀 Build Safari extension (iOS mobile)
        script: |
          echo "Building Safari extension..."
          xcodebuild -project "./DexscreenerTraderExtension/DexscreenerTraderExtension.xcodeproj" \
            -scheme "DexscreenerTraderExtension (iOS)" \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO

      - name: 📦 Export unsigned IPA for AltStore / EonHub
        script: |
          echo "Creating unsigned IPA..."
          mkdir -p build/ipa
          xcrun xcodebuild -exportArchive \
            -archivePath build/${APP_NAME}.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>ad-hoc</string></dict></plist>') || true
          echo "✅ Unsigned IPA ready for AltStore / EonHub"

    artifacts:
      - build/ipa/*.ipa
