workflows:
  safari_extension_build:
    name: Build Safari Extension
    environment:
      xcode: latest
      vars:
        EXTENSION_NAME: "Dexscreener-trader-extension"
    scripts:
      # Step 1 — Verify manifest exists
      - name: Check manifest.json
        script: |
          if [ ! -f "manifest.json" ]; then
            echo "❌ manifest.json not found. Please add it to project root."
            exit 1
          fi

      # Step 2 — Create output folder
      - name: Prepare build directory
        script: |
          mkdir -p build/safari

      # Step 3 — Convert Chrome extension to Safari
      - name: Convert Chrome extension to Safari
        script: |
          xcrun safari-web-extension-converter . \
            --project-location build/safari \
            --app-name "$EXTENSION_NAME" \
            --no-open \
            --force

      # Step 4 — Build Safari app
      - name: Build Safari extension app
        script: |
          cd build/safari/"$EXTENSION_NAME"
          xcodebuild -scheme "$EXTENSION_NAME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    artifacts:
      - build/safari/**

    publishing:
      email:
        recipients:
          - your@email.com
