workflows:
  safari_extension_altstore:
    name: Safari Extension for AltStore
    environment:
      vars:
        APP_NAME: "DexscreenerTrader"
    scripts:
      - name: 🧹 Clean workspace
        script: |
          rm -rf build || true
          mkdir -p build

      - name: 🧩 Prepare Safari Extension project
        script: |
          echo "Preparing Safari Extension project..."

      - name: 🚀 Build unsigned Safari extension
        script: |
          echo "Building unsigned IPA..."
          mkdir -p build/ipa
          xcrun xcodebuild -exportArchive \
            -archivePath build/${APP_NAME}.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>ad-hoc</string></dict></plist>')

      - name: 📦 Package and rename IPA
        script: |
          VERSION=$(date +"%Y%m%d_%H%M")
          FINAL_NAME="${APP_NAME}_${VERSION}.ipa"
          mv build/ipa/*.ipa "build/${FINAL_NAME}"
          zip -j "build/${FINAL_NAME}.zip" "build/${FINAL_NAME}"
          echo "✅ Packaged and renamed ${FINAL_NAME}"

    artifacts:
      - build/*.ipa
      - build/*.zip

    publishing:
      scripts:
        - name: 📤 Upload IPA for AltStore
          script: |
            echo "IPA uploaded! Copy the download link from Artifacts below 👇"
