workflows:
  ios_unsigned_build:
    name: Build Unsigned IPA for AltStore
    max_build_duration: 60
    environment:
      groups:
        - codemagic_credentials  # Contains CM_API_TOKEN
      vars:
        APP_NAME: "DexscreenerTrader"
        BUNDLE_ID: "com.millitradez.dexscreenertrader"
        XCODE_WORKSPACE: "DexscreenerTrader.xcworkspace"
        XCODE_SCHEME: "DexscreenerTrader"
        BUILD_DIR: "build"
      xcode: latest
      cocoapods: default
    scripts:
      - name: 🚀 Prepare Safari Extension project
        script: |
          echo "Preparing Dexscreener Safari extension for unsigned export..."
          if [ ! -d "./DexscreenerTraderExtension" ]; then
            echo "❌ DexscreenerTraderExtension folder not found. Please ensure project is in repo root."
            exit 66
          fi

      - name: 🧱 Build Xcode project (clean)
        script: |
          echo "Cleaning project..."
          xcodebuild -project "./DexscreenerTraderExtension/DexscreenerTraderExtension.xcodeproj" \
          -scheme "${XCODE_SCHEME}" clean

      - name: 📦 Archive Xcode build
        script: |
          echo "Archiving build..."
          mkdir -p "${BUILD_DIR}"
          xcodebuild -project "./DexscreenerTraderExtension/DexscreenerTraderExtension.xcodeproj" \
          -scheme "${XCODE_SCHEME}" \
          -archivePath "${BUILD_DIR}/${APP_NAME}.xcarchive" \
          archive

      - name: 🧩 Create unsigned IPA for AltStore
        script: |
          echo "Creating unsigned IPA..."
          mkdir -p "${BUILD_DIR}/ipa"
          xcrun xcodebuild -exportArchive \
            -archivePath "${BUILD_DIR}/${APP_NAME}.xcarchive" \
            -exportPath "${BUILD_DIR}/ipa" \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>ad-hoc</string></dict></plist>')
          echo "✅ Unsigned IPA ready for AltStore"

      - name: 📤 Compress and rename IPA
        script: |
          IPA_PATH="${BUILD_DIR}/ipa/${APP_NAME}.ipa"
          if [ -f "$IPA_PATH" ]; then
            ZIP_PATH="${BUILD_DIR}/${APP_NAME}_$(date +%Y%m%d_%H%M%S).zip"
            mv "$IPA_PATH" "$ZIP_PATH"
            echo "📦 IPA renamed to $ZIP_PATH"
          else
            echo "❌ IPA not found!"
            exit 1
          fi

    artifacts:
      - build/ipa/*.ipa
      - build/*.zip

    publishing:
      scripts:
        - name: 🔗 Generate shareable artifact link
          script: |
            echo "Generating public link for AltStore import..."
            echo "You can upload the .ipa or .zip to any file host (e.g. Dropbox, Google Drive, or GitHub Releases)"
            echo "Then open AltStore > My Apps > + (add) > choose the downloaded IPA file."
