workflows:
  web_extension_unsigned_build:
    name: DexscreenerTrader Unsigned Web Build
    max_build_duration: 30
    environment:
      groups:
        - codemagic_credentials
      vars:
        APP_NAME: "DexscreenerTrader"
        BUILD_DIR: "build"
    scripts:
      - name: 🧹 Clean workspace
        script: |
          echo "Cleaning workspace..."
          rm -rf "$BUILD_DIR"
          mkdir -p "$BUILD_DIR"

      - name: 📁 Prepare web extension files
        script: |
          echo "Preparing web extension files for DexscreenerTrader..."
          mkdir -p "$BUILD_DIR"
          cp -r content Content icons popup *.js *.html *.json *.md "$BUILD_DIR" 2>/dev/null || true
          echo "✅ Files copied to build directory."

      - name: 🧩 Package unsigned web build
        script: |
          cd "$BUILD_DIR"
          BUILD_NAME="${APP_NAME}_$(date +%Y%m%d_%H%M%S)"
          zip -r "${BUILD_NAME}.zip" .
          mv "${BUILD_NAME}.zip" ../
          echo "✅ Created unsigned build: ${BUILD_NAME}.zip"

      - name: 📤 Generate shareable artifact link
        script: |
          echo "Generating shareable artifact link..."
          ls -lh ../*.zip
          echo "You can find your build in the 'Artifacts' tab after completion."

    artifacts:
      - "*.zip"

    publishing:
      scripts:
        - name: 🔗 Auto-publish build link
          script: |
            echo "Build complete — share your ZIP artifact from Codemagic UI or via generated link."
