workflows:
  safari_extension_convert:
    name: Safari Extension Auto-Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      vars:
        EXTENSION_NAME: "Dexscreener Trader Extension"
    scripts:
      - name: 🧹 Clean workspace
        script: |
          rm -rf safari_project
          mkdir safari_project

      - name: 🧩 Convert Chrome extension to Safari
        script: |
          echo "Converting Chrome extension to Safari..."
          # Make sure we’re in the project root that has manifest.json
          if [ ! -f "manifest.json" ]; then
            echo "manifest.json not found in root. Checking nested folders..."
            cd $(find . -name manifest.json -exec dirname {} \; | head -n 1)
          fi

          xcrun safari-web-extension-converter . \
            --project-location ../safari_project \
            --app-name "${EXTENSION_NAME}" \
            --no-prompt \
            --force

      - name: 🚀 Build Safari extension app
        script: |
          echo "Building Safari extension..."
          cd safari_project
          SCHEME=$(xcodebuild -list | grep -A1 "Schemes:" | tail -n1 | xargs)
          echo "Detected scheme: $SCHEME"
          if [ -z "$SCHEME" ]; then
            echo "❌ No scheme detected — listing contents for debug:"
            ls -R
            exit 1
          fi
          xcodebuild -scheme "$SCHEME" -configuration Release CODE_SIGNING_ALLOWED=NO

    artifacts:
      - safari_project/build/Release/
    publishing:
      email:
        recipients:
          - tradezconsulting@icloud.com
