workflows:
  safari_extension_ios_free:
    name: Safari Extension iOS (Free build for AltStore/EonHub)
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "MySafariExtension"
        BUNDLE_ID: "com.yourname.mysafariextension"
      xcode: 16.0
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: $BUNDLE_ID
        automatic_code_signing: false

    scripts:
      - name: 🧹 Clean workspace
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          echo "Workspace cleaned"

      - name: 🧩 Verify and convert Chrome extension (if applicable)
        script: |
          if [ -d "chrome_extension" ]; then
            echo "Converting Chrome extension to Safari..."
            xcrun safari-web-extension-converter chrome_extension --project-location safari_project --app-name "$APP_NAME" --bundle-identifier "$BUNDLE_ID" --swift --force
          else
            echo "No Chrome extension found, skipping..."
          fi

      - name: 🚀 Build Safari extension (iOS mobile)
        script: |
          cd safari_project || exit 1
          xcodebuild -scheme "$APP_NAME (iOS)" \
            -sdk iphoneos \
            -configuration Release \
            clean build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            -archivePath $CM_BUILD_DIR/$APP_NAME.xcarchive

      - name: 📦 Export unsigned .ipa
        script: |
          mkdir -p $CM_BUILD_DIR/export
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/$APP_NAME.xcarchive \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
            </dict>
            </plist>') \
            -exportPath $CM_BUILD_DIR/export \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa

    publishing:
      email:
        recipients:
          - your@email.com
