workflows:
  safari_extension_convert:
    name: Dexscreener Trader iOS Extension
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      vars:
        APP_NAME: "DexscreenerTraderExtension"

    scripts:
      - name: 🧹 Clean workspace
        script: |
          echo "Cleaning build folder..."
          rm -rf build || true

      - name: 🧩 Prepare Safari Extension project
        script: |
          echo "Preparing extension files..."
          mkdir -p safari_project
          cp -R extension/* safari_project/
          echo "✅ Safari project folder ready."

      - name: 🚀 Build unsigned Safari extension
        script: |
          echo "Building Safari extension for iOS (unsigned)..."
          xcodebuild -project "./DexscreenerTraderExtension/DexscreenerTraderExtension.xcodeproj" \
            -scheme "DexscreenerTraderExtension (iOS)" \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          echo "✅ Build complete (unsigned)."

      - name: 📦 Export unsigned IPA for AltStore / EonHub
        script: |
          echo "Creating unsigned IPA..."
          mkdir -p build/ipa
          xcrun xcodebuild -exportArchive \
            -archivePath build/${APP_NAME}.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
            <plist version="1.0">
              <dict>
                <key>method</key><string>ad-hoc</string>
              </dict>
            </plist>') || true
          echo "✅ Unsigned IPA exported."

      - name: 🗜️ Package final IPA
        script: |
          echo "Packaging unsigned IPA..."
          cd build/ipa
          mv *.ipa "${APP_NAME}_unsigned.ipa" || true
          zip -r "${APP_NAME}_unsigned.zip" "${APP_NAME}_unsigned.ipa" || true
          echo "✅ IPA packaged for AltStore / EonHub."

    artifacts:
      - build/ipa/*.ipa
      - build/ipa/*.zip
