workflows:
  safari_extension_convert:
    name: Safari Mobile Extension Auto-Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: 16.4
      vars:
        EXTENSION_NAME: "DexscreenerTraderExtension"
    scripts:
      - name: 🧹 Clean workspace
        script: |
          rm -rf safari_project
          mkdir safari_project

      - name: 🧩 Verify and convert Chrome extension
        script: |
          echo "🔍 Searching for manifest.json..."
          MANIFEST_PATH=$(find . -name manifest.json | head -n 1)
          if [ -z "$MANIFEST_PATH" ]; then
            echo "❌ No manifest.json found — cannot continue."
            exit 1
          fi

          echo "✅ Found manifest at: $MANIFEST_PATH"
          EXT_DIR=$(dirname "$MANIFEST_PATH")
          echo "Converting extension in: $EXT_DIR"

          cd "$EXT_DIR"
          xcrun safari-web-extension-converter . \
            --project-location "$PWD/../safari_project" \
            --app-name "${EXTENSION_NAME}" \
            --no-prompt \
            --force

          echo "✅ Conversion complete. Checking output..."
          ls -la ../safari_project || echo "⚠️ safari_project folder is empty!"

      - name: 🚀 Build Safari extension (iOS mobile)
        script: |
          echo "📦 Building Safari iOS extension..."
          cd ../safari_project || { echo "❌ safari_project missing"; exit 1; }

          echo "Listing contents for debug:"
          ls -R

          PROJECT=$(find . -name "*.xcodeproj" | head -n 1)
          if [ -z "$PROJECT" ]; then
            echo "❌ No Xcode project found after conversion."
            exit 1
          fi

          echo "✅ Found project: $PROJECT"

          SCHEME=$(xcodebuild -list -project "$PROJECT" | grep "iOS (App)" | head -n 1 | xargs)
          if [ -z "$SCHEME" ]; then
            echo "⚠️ iOS (App) scheme not found, falling back to first detected scheme..."
            SCHEME=$(xcodebuild -list -project "$PROJECT" | grep -A1 "Schemes:" | tail -n1 | xargs)
          fi

          echo "Detected scheme: $SCHEME"

          if [ -z "$SCHEME" ]; then
            echo "❌ No valid iOS scheme found — cannot continue."
            exit 1
          fi

          echo "🚀 Starting iOS build..."
          xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO

          echo "✅ iOS Safari extension built successfully!"
          ls -R build || echo "⚠️ Build folder missing!"

    artifacts:
      - safari_project/build/Release-iphoneos/
    publishing:
      email:
        recipients:
          - tradezconsulting@icloud.com
