workflows:
  safari_extension_build:
    name: Dexscreener Safari Extension Build
    environment:
      xcode: latest
      vars:
        EXTENSION_NAME: "DexscreenerTraderExtension"
        BUNDLE_IDENTIFIER: "com.tradezconsulting.dexscreenertrader"
        APPLE_ID: "Tradezconsulting@icloud.com"
    scripts:
      - name: Verify manifest.json and prepare
        script: |
          echo "Checking manifest.json..."
          if [ ! -f "manifest.json" ]; then
            echo "❌ manifest.json not found!"; exit 1;
          fi
          echo "✅ manifest.json found"

      - name: Convert Chrome extension to Safari
        script: |
          mkdir -p safari_project
          echo "Converting Chrome extension → Safari format..."
          xcrun safari-web-extension-converter . \
            --project-location safari_project \
            --app-name "$EXTENSION_NAME" \
            --bundle-identifier "$BUNDLE_IDENTIFIER" \
            --apple-id "$APPLE_ID" \
            --force --no-prompt
          echo "✅ Conversion complete"

      - name: Detect available schemes
        script: |
          echo "🔍 Detecting schemes..."
          cd safari_project || exit 1
          xcodebuild -list

      - name: Build Safari extension app
        script: |
          echo "🚀 Building Safari app..."
          cd safari_project || exit 1
          xcodebuild -scheme "$EXTENSION_NAME (macOS)" \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          echo "✅ Safari app build complete"

      - name: Auto-register extension with Safari
        script: |
          echo "🔧 Registering extension for Safari..."
          cd safari_project/build/Release || exit 1
          APP_PATH=$(find . -name "*.app" | head -n 1)
          if [ -n "$APP_PATH" ]; then
            echo "Found app: $APP_PATH"
            open "$APP_PATH"
            echo "✅ Extension app launched — check Safari > Settings > Extensions"
          else
            echo "❌ App not found in Release folder"
            exit 1
          fi

    artifacts:
      - safari_project/build/Release/*.app
      - safari_project/build/Release/*.safariextz
    publishing:
      email:
        recipients:
          - Tradezconsulting@icloud.com
        notify:
          success: true
          failure: true
