workflows:
  altstore_build:
    name: Dexscreener AltStore Build
    environment:
      vars:
        APP_NAME: "DexscreenerTrader"
        BUNDLE_ID: "com.tradezconsulting.dexscreener"
        TEAM_ID: "YOUR_APPLE_TEAM_ID"
        # ⬇️ Replace these two after your first build
        PUBLIC_IPA_URL: "https://placeholder.com/ipa"  # <-- Replace with IPA artifact link from Codemagic
        APP_ICON_URL: "https://placeholder.com/icon.png"  # <-- Replace with your app icon URL (can be from GitHub or Imgur)
    scripts:
      - name: Clean workspace
        script: |
          rm -rf build || true
          mkdir -p build/ipa

      - name: Prepare Safari Extension project
        script: |
          echo "Preparing Dexscreener Safari extension for unsigned export..."
          xcodebuild -project Dexscreener.xcodeproj -scheme "${APP_NAME}" clean

      - name: Build unsigned Safari extension
        script: |
          echo "Building unsigned IPA..."
          xcodebuild -project Dexscreener.xcodeproj \
            -scheme "${APP_NAME}" \
            -configuration Release \
            -archivePath build/${APP_NAME}.xcarchive archive

      - name: Export unsigned IPA for AltStore
        script: |
          echo "Creating unsigned IPA..."
          xcrun xcodebuild -exportArchive \
            -archivePath build/${APP_NAME}.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>ad-hoc</string></dict></plist>') || true
          cd build/ipa
          zip -r ${APP_NAME}_unsigned.zip ${APP_NAME}.ipa
          echo "✅ Unsigned IPA ready for AltStore / EonHub"

      - name: Generate AltStore manifest
        script: |
          echo "Generating manifest.plist..."
          cat > manifest.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>items</key>
            <array>
              <dict>
                <key>assets</key>
                <array>
                  <dict>
                    <key>kind</key><string>software-package</string>
                    <key>url</key><string>${PUBLIC_IPA_URL}</string>
                  </dict>
                  <dict>
                    <key>kind</key><string>display-image</string>
                    <key>url</key><string>${APP_ICON_URL}</string>
                  </dict>
                </array>
                <key>metadata</key>
                <dict>
                  <key>bundle-identifier</key><string>${BUNDLE_ID}</string>
                  <key>bundle-version</key><string>1.0</string>
                  <key>kind</key><string>software</string>
                  <key>title</key><string>${APP_NAME}</string>
                </dict>
              </dict>
            </array>
          </dict>
          </plist>
          EOF
          echo "✅ manifest.plist ready for AltStore"

    artifacts:
      - build/ipa/${APP_NAME}.ipa
      - build/ipa/${APP_NAME}_unsigned.zip
      - build/ipa/manifest.plist
