workflows:
  safari_extension_build:
    name: Build Safari Extension (Non-Interactive)
    environment:
      xcode: latest
      vars:
        EXTENSION_NAME: "Dexscreener-trader-extension"
    scripts:
      - name: Ensure manifest.json exists
        script: |
          if [ ! -f "manifest.json" ]; then
            echo "❌ No manifest.json found. Please add it to root."
            exit 1
          fi

      - name: Prepare build directory
        script: |
          mkdir -p build/safari

      - name: Convert Chrome extension to Safari (non-interactive)
        script: |
          xcrun safari-web-extension-converter . \
            --project-location build/safari \
            --app-name "$EXTENSION_NAME" \
            --no-open \
            --no-prompt \
            --force

      - name: Build Safari extension app
        script: |
          cd build/safari/"$EXTENSION_NAME"
          xcodebuild -scheme "$EXTENSION_NAME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    artifacts:
      - build/safari/**
